### ISSUE TITLE
Tortoise and Hare

### ISSUE THREAD

**Issue by asterite** [nzoschke/gistdeck#12]
I would so use this if it could show a Tortoise and a Hare at the bottom, like what rabbit does. (hare shows slide number over total slides, tortoise shows time, so you can limit your presentation to some time and see your progress and time left at the same time)

Can I try to implement it and submit a pull request?

**Comment by seaofclouds** [comment]
Sure- have at. :)  
- Todd

##

**Comment by asterite** [comment]
Ok, here it is:

https://github.com/asterite/gistdeck

Clone it, open the gist.html file and press "T" on your keyboard. It will ask you how many minutes the presentation will last. Then a tortoise and a hare will appear at the bottom, together with two flags (start and goal).

In rabbit the flags are rectangular and have the numbers 1 and total number of slides, but I couldn't find those images, just the triangular flags (maybe rabbit draws that, it doesn't use an image).

https://raw.github.com/shockers/rabbit/master/sample/ppt/hare-and-tortoise-middle.png

Well, we should ask Kouhei Sutou if we can use his images. Or, if you think they don't match the style of your presentations (your css) you can change it to something else, but at least the logic is there.

I don't know if the css will work because I don't know how image urls are solved.

Now I don't need any special software to have nice presentations + rabbit and hare. Yay! THANK YOU!

**Comment by asterite** [comment]
In the code, there' a tickInterval variable. Each tickInterval seconds the tortoise is re-drawn. I put it to one second, but maybe 5 or 10 seconds is better (so it doesn't distract viewers), but you choose that value...

**Comment by nzoschke** [comment]
Thanks for the request and code, but Gistdeck aims to be as simple as possible. Therefore this feature will not be added.
