### ISSUE TITLE
Return to bare gist

### ISSUE THREAD

**Issue by freeformz** [nzoschke/gistdeck#13]
It would be nice if pressing the bookmarklet a second time returned you to the raw gist.

**Comment by henrahmagix** [comment]
+1, but would like the Esc key to do the same.

**Comment by vitorbal** [comment]
One solution could also be adding the transformation from a raw gist to a presentation to the browser history state. This way pressing back would return you to the raw gist again.

**Comment by henrahmagix** [comment]
Very nice work @vitorbal =D

**Comment by vitorbal** [comment]
@henrahmagix thanks! :)
