### ISSUE TITLE
Not compatible with new Gist site

### ISSUE THREAD

**Issue by tybenz** [nzoschke/gistdeck#14]
https://github.com/blog/1276-welcome-to-a-new-gist

Gistdeck no longer works... bummer.

**Comment by asteritedummy** [comment]
Oh, I bumped into this too... :-(

Maybe it's just about changing the CSS stylesheet...

**Comment by nzoschke** [comment]
Looks like it's mostly the CSS.

bc777dd5 brings in HTML with the new gist layout to develop against. Open this locally and you can refresh the page to iterate on Javascript / CSS.

I took out the CSS that used to hide the Gist UI and there's some semblance of a deck again.

**Comment by henrahmagix** [comment]
@nzoschke `.bubble` is being hidden as part of `/* hide github interface */`. That class is being applied to each file div in the file column. Since `.markdown-body` is now within `.bubble`, all the content is being hidden.

Working on a fix but I'm struggling to remember how it looked before =)

**Comment by henrahmagix** [comment]
@nzoschke There were also two instances of id/class names changing (I assume), so a working version is in #15. Let me know if there's anything I might have missed =)

**Comment by nzoschke** [comment]
Thanks a ton, I just merged and released this.

However I do see a few small issues.

Previously, the #owner section was a title slide with the gist username, gravatar and description. Now it seems that the description is extracted, but not converted to a slide, and not the first element focused on. On first look, the HTML layout is significantly different here now, so not sure how easy it is to restore the old behavior.

Also, when testing on the online reference gist, https://gist.github.com/b273f7a3089b1a238f5a, the comment box is not removed from the final slide.

**Comment by henrahmagix** [comment]
Cheers =)

I see what you mean. Do you or @seaofclouds have any screenshots of what Gistdeck looked like previously? I'll get onto fixing that and removing the comment box very soon.

**Comment by nzoschke** [comment]
Thanks again for your patches, it's back to working quite well!

**Comment by henrahmagix** [comment]
![](http://1.bp.blogspot.com/-xDy_zx18R5g/UPwwTsdyRVI/AAAAAAAAGa4/elrNYEiZPLg/s1600/its-working-its-working.gif)
