### ISSUE TITLE
Firefox Compatibility

### ISSUE THREAD

**Issue by nzoschke** [nzoschke/gistdeck#5]
<a href="http://news.ycombinator.com/item?id=4149316">Reported by iand on HN</a>:

> Doesn't work for me - get the reformatted page but keys don't work. Linux FF 10.0.5

**Comment by Gozala** [comment]
Does not works on FF

**Comment by ethanwhite** [comment]
I can confirm this issue on both Ubuntu 12.04 and Windows 7 using Firefox 13.0.1.

**Comment by ngsankha** [comment]
Yes. I am also having the same problem on Ubuntu 12 with Firefox 13. Did not try it on Firefox for Windows yet though!

**Comment by nzoschke** [comment]
#10 fixed this. Thanks Sankha!
