### ISSUE TITLE
Left and Right keys don't work for navigation

### ISSUE THREAD

**Issue by ngsankha** [nzoschke/gistdeck#9]
I am on Ubuntu 12, Firefox 13. When I try to view the gist as a presentation I cannot navigate through the individual slides with the Left and Right arrow keys. Instead I need to scroll through the presentation with up and down keys as if it on big page.

**Comment by seaofclouds** [comment]
Thanks for the report!

There is an issue posted that addresses a problem with larger screens. There is another issue that covers firefox compatibility. If your issue is related to one of those issues, I encourage you to up vote and comment accordingly.

Cheers! 

##

**Comment by ngsankha** [comment]
Yes, since the issues are same, I'll upvote that and I am closing this.
